### ISSUE TITLE
connecting keycloak to a local DB

### ISSUE THREAD

**Issue by mazbeh** [lukaszbudnik/keycloak-kubernetes#18]
Hi every body,
i am new to kubenetes. I have recently tried to connect the keycloak containers ( pods )  to a local DB ( postgres ). But the connection will be refused. 
Do you know how can i connect the pod to a postgresql DB on the host ( on the host works every thing fine )? 

Thanks alot !

**Comment by lukaszbudnik** [comment]
Hi @mazbeh,
I'm closing this pull request because it's not related to the project. As you are new to Kubernetes you need to go through a few tutorial to better understand it. In short: it's tricky to connect to any services running on localhost from Kubernetes. In this situation I highly recommend that you follow the instructions in the README.md to install both Keycloak and PostgreSQL in Kubernetes.

**Comment by mazbeh** [comment]
ok, thanks for replying .
