### ISSUE TITLE
Error while using postgres-ha

### ISSUE THREAD

**Issue by Nehoko** [lukaszbudnik/keycloak-kubernetes#21]
I tried to use what you suggest in this repo, but it doesn't work for me (I actually can't remember issue).
I've changed bitnami/postgres-ha chart to bitnami/postgresql and that worked for me. There was some issues with password variable naming inside of secret (postgres-password instead of postgresql-password).

Maybe it is a issue with my silicon chip (m2) or it's chart issue.

**Comment by lukaszbudnik** [comment]
hey @Nehoko, That's the first time I hear about this issue. I have enabled automatic deploys as a part of github actions (https://github.com/lukaszbudnik/keycloak-kubernetes/blob/main/.github/workflows/deployment.yaml) I was also deploying it to AWS EKS and never had this issue.
May be worth submitting a ticket to the bitnami/postgres-ha helm contributors?

**Comment by Nehoko** [comment]
> hey @Nehoko, That's the first time I hear about this issue. I have enabled automatic deploys as a part of github actions (https://github.com/lukaszbudnik/keycloak-kubernetes/blob/main/.github/workflows/deployment.yaml) I was also deploying it to AWS EKS and never had this issue.
> May be worth submitting a ticket to the bitnami/postgres-ha helm contributors?

probably it is, actually. I should go to them. But anyway could you add something like note in your README.md just to describe my case? Will appreciate that.

**Comment by lukaszbudnik** [comment]
@Nehoko I was troubleshooting failing GitHub workflow action and I saw that the keycloak pods weren't created because of the secret having different key. By quickly checking bitnami github repo I saw that it was updated: https://github.com/bitnami/charts/commit/2bed17e3241dc3a04e526e28746d8876da7a1acd the commit message says "backwards compat postgres-password" but guess something went wrong :)
I will fix that over the weekend.

**Comment by Nehoko** [comment]
Yeah, it's good to know, but that was not the main issue. It was more about compatibility with my processor (Apple Silicon).
