### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by Quadrisheriff** [lukaszbudnik/keycloak-kubernetes#24]
Hi @lukaszbudnik, thanks a lot for all you have done for the community. I have successfully deployed Keycloak on an AWS EKS cluster by following your tutorial and I'm very grateful for that.  Now I want to add a custom theme to the deployment.

How would you advise that I go about the custom theme part

**Comment by jainmohit** [comment]
@Quadrisheriff did you setup the aws domain in route 53 or have you got domain on godaddy or any other platform apart from aws as i am unable to access the ELB url from internet.

**Comment by lukaszbudnik** [comment]
hi @Quadrisheriff 

Regarding your questions:

1. in order to deploy a custom theme you need to build your container with the theme installed there - you would need to create a `Dockerfile`, use official Keycloak docker image as the base and install your theme there, once this is built, publish it to AWS ECR, and then update Kubernetes deployment to use this new image
2. I used Amazon Route53 for DNS

**Comment by lukaszbudnik** [comment]
Closing as no follow up questions.
